apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-app
  namespace: test
  labels:
    app: scrapper-app
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: scrapper-app
  template:
    metadata:
      labels:
        app: scrapper-app
        version: v1
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: role
                operator: In
                values: ["workload"]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - scrapper-app
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: huawei-swr-secret
      containers:
        - name: scrapper-app
          image: swr.ap-southeast-2.myhuaweicloud.com/live/ghulammuzzmit/scrapper:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:   
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: scrapper-app
  namespace: test
  labels:
    app: scrapper-app
spec:
  selector:
    app: scrapper-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP