apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mrscrapper-vs
  namespace: istio-system
spec:
  hosts:
  - "mrscrapper.aswaja-nulife.com"
  gateways:
  - istio-system/public-gateway
  http:
  - route:
    - destination:
        host: mrscrapper.test.svc.cluster.local
        port:
          number: 3000